[build]
  command = "npm run build"
  publish = "dist"
[[plugins]]
  package = "netlify-plugin-prerender-spa"
  [plugins.inputs]
  source = "dist"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
